on:
  issues:
    types:
      - labeled
      
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Post pacific update
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://httpbin.org/post'
          method: 'POST'
          data: "{\"data\": \"Issue body: ${{ github.event.issue.body }}\"}"
